"""empty message

Revision ID: 511ca3f0a6c5
Revises: cc2bebf9ba6c
Create Date: 2020-03-19 14:47:13.198011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511ca3f0a6c5'
down_revision = 'cc2bebf9ba6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('actors_movies',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors_movies')
    op.drop_table('movie')
    # ### end Alembic commands ###
